from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class FeedbackCategory(str, Enum):
    FACTUAL = "factual"  # The LLM got a technical detail wrong (e.g., wrong ResNet layer count)
    STYLE = "style"  # The LLM was too wordy or didn't follow the preferred tone
    CLARITY = "clarity"  # The explanation was confusing
    CITATION = "citation"  # The source ID was incorrect or missing
    OTHER = "other"


class FeedbackSubmitRequest(BaseModel):
    """The schema for the incoming API request from the frontend/operator."""

    interaction_id: str = Field(..., description="ID of the original generation")
    query: str = Field(..., description="The original user prompt")
    original_draft: str = Field(..., description="The draft generated by the LLM")
    edited_version: str = Field(..., description="The version after human edits")
    context_ids: List[str] = Field(..., description="List of citation IDs used")


class FeedbackEntry(BaseModel):
    """The schema for a single human-in-the-loop alignment record stored in the database."""

    # Traceability
    interaction_id: str = Field(
        ..., description="Unique ID linking to the original request"
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # The Content Delta
    query: str = Field(..., description="The original user input")
    original_draft: str = Field(..., description="The unedited LLM output")
    edited_version: str = Field(
        ..., description="The final version after human correction"
    )

    # ML Signal Extraction
    category: FeedbackCategory = Field(
        default=FeedbackCategory.OTHER,
        description="Type of improvement made by the human",
    )
    edit_ratio: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Levenstein-based similarity ratio between original and edited",
    )

    # Context for Future Training
    context_used: List[str] = Field(
        default_factory=list,
        description="The source IDs available to the LLM during generation",
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None, description="Model version, temperature, and other hyperparameters"
    )

    @field_validator("edit_ratio")
    @classmethod
    def validate_ratio(cls, v):
        # If ratio is 1.0, no changes were made.
        return round(v, 4)


class FeedbackSummary(BaseModel):
    """Used for reporting system performance over time."""

    total_edits: int
    factual_accuracy_rate: float  # (Total - Factual Edits) / Total
    average_edit_distance: float
